---
- name: Setup admin production UFW
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Allow everything and enable UFW
      community.general.ufw:
        state: enabled
        policy: allow
    - name: ufw allow incoming
      community.general.ufw:
        direction: incoming
        proto: any
        policy: allow
        
    - name: deny access to prod
      community.general.ufw:
        direction: out
        proto: any
        policy: deny
        src: any
        dest: 10.0.236.0/24
